version: '3.8'
services:
  web:
    container_name: nginx
    image: nginx:latest
    restart: always
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - npm
  app:
    container_name: npm_server
    restart: unless-stopped
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    networks:
      - npm
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt
networks:
  npm:
    name: npm
    driver: bridge
volumes:
  data:
  letsencrypt:


