version: "3.3"

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    init: true
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - npm
      - portainer
networks:
  portainer:
    name: portainer
    driver: bridge
  npm:
    external: true
volumes:
  portainer_data:
